### ISSUE TITLE
Got warning if I use `floatingActionButton`.

### ISSUE THREAD

**Issue by tuanbs** [Kounex/provider_theme_switcher#1]
Hi,

I see if I use `floatingActionButton` and switching theme at runtime, I got the following warnings:
```bash
flutter: Warning: The support for configuring the foreground color of FloatingActionButtons using ThemeData.accentIconTheme has been deprecated. Please use ThemeData.floatingActionButtonTheme instead. See https://flutter.dev/go/remove-fab-accent-theme-dependency. This feature was deprecated after v1.13.2.
flutter: Warning: The support for configuring the foreground color of FloatingActionButtons using ThemeData.accentIconTheme has been deprecated. Please use ThemeData.floatingActionButtonTheme instead. See https://flutter.dev/go/remove-fab-accent-theme-dependency. This feature was deprecated after v1.13.2.
flutter: Warning: The support for configuring the foreground color of FloatingActionButtons using ThemeData.accentIconTheme has been deprecated. Please use ThemeData.floatingActionButtonTheme instead. See https://flutter.dev/go/remove-fab-accent-theme-dependency. This feature was deprecated after v1.13.2.
flutter: Warning: The support for configuring the foreground color of FloatingActionButtons using ThemeData.accentIconTheme has been deprecated. Please use ThemeData.floatingActionButtonTheme instead. See https://flutter.dev/go/remove-fab-accent-theme-dependency. This feature was deprecated after v1.13.2.
```

#### `home.dart`
```dart
class HomeView extends StatelessWidget {
// ...
floatingActionButton: FloatingActionButton(
        onPressed: () {},
        child: Icon(Icons.add),
      ),
}
```

**Comment by Kounex** [comment]
Greetings!

As the warning indicates, this happens because you probably set the `accentIconTheme` property to change the color of your `FloatingActionButtons`! You could show me your `MaterialApp` Widget where you set your `Theme` so we could look at it together!

But generally use the `floatingActionButtonTheme` property of `ThemeData` now, since this is the new way of doing this! :)

**Comment by tuanbs** [comment]
Hi,

I use your example and just added the FAB then got this warning.

**Comment by Kounex** [comment]
Okay i can see what you mean. This happens when we switch to the "Custom" Theme. I'm using `ThemeData.dark()` as the base and call `copyWith` on it to make my own changes. Internally the `accentIconTheme` property is set via `copyWith` and FABs still reference to this which is deprecated.

I "fixed" this by explicitly set the `floatingActionButtonTheme` property in `ThemeData` so FABs use this correctly - you can just pull this repo again! :)

**Comment by tuanbs** [comment]
Hi,

I happens to the light and dark theme as well. I mean switching theme from
one to another then it causes the warning.

**Comment by Kounex** [comment]
On which branch are you? I tested it on `beta` and it does not happen for me. You can check this with `flutter channel`. You can call `flutter channel beta` to change to beta as well and then use `flutter upgrade` to get the current version of this branch!

**Comment by tuanbs** [comment]
I’m using the latest version and on stable branch wishing is the official
one I think.

**Comment by Kounex** [comment]
As I wrote earlier this is actually an internal problem since I'm using the `light()` and `dark()` method of `ThemeData` which do not apply the new `floatingActionButtonTheme` but have the `accentIconTheme` so FABs trigger this warning. I added the `floatingActionButtonTheme` to the themes as well so it won't trigger the warning for now - this won't be necessary in the future after flutter adjusted this internally.

You can pull again! Should work now

**Comment by Kounex** [comment]
Done
